use_frameworks!
platform :ios, '9.0'

target 'IpfsApi_Example' do
  pod 'IpfsApi', :path => '../'
  pod 'Moya/RxSwift', '~> 11.0'
  pod 'Hero'
  pod 'FontAwesomeKit'
  pod 'Viewer'
  pod 'IGListKit'
  pod 'IQKeyboardManagerSwift'
  pod 'TUSafariActivity'
  pod 'PopupDialog'
  
  target 'IpfsApi_Tests' do
    inherit! :search_paths

  end
  
  post_install do |installer|
      installer.pods_project.build_configurations.each do |config|
          config.build_settings.delete('CODE_SIGNING_ALLOWED')
          config.build_settings.delete('CODE_SIGNING_REQUIRED')
      end
  end
end
